In [1]:
list = [1,2,3]
list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(list)

In [4]:
arr

array([1, 2, 3])

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(2)

array([0.16513002, 0.43183599])

In [26]:
np.random.rand(3,3)

array([[0.31730778, 0.02395528, 0.18322126],
       [0.28979288, 0.3708727 , 0.43928482],
       [0.25154038, 0.29025264, 0.91299468]])

In [27]:
np.random.randn(3,3)

array([[ 0.23409698,  1.448411  ,  0.67358556],
       [ 0.22720451,  0.75147929,  0.27904084],
       [ 0.16909025, -0.54184364, -1.49006167]])

In [29]:
np.random.randint(1,100)

96

In [30]:
np.random.randint(1,100,10)

array([87,  9, 64, 63, 23, 25, 38, 50, 87, 14])

In [31]:
np.random.randint(1,100,[5,5])

array([[10, 44, 72, 35, 26],
       [72, 90, 95, 60, 69],
       [21, 98,  3, 51, 53],
       [42, 42, 78, 40,  1],
       [31, 17, 81,  5, 75]])

In [32]:
x = np.arange(50)

In [33]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
y = np.random.randint(0,100,50)
y

array([53, 97, 41, 52, 46, 96, 97, 53, 79, 54, 12, 98, 82, 62, 88, 34, 74,
       41, 14, 15, 25, 73, 28, 23, 57, 34, 95, 64, 33,  3, 16,  6, 14, 98,
       20, 76, 47, 47, 39, 26, 45, 70, 42, 18, 25, 42,  7, 80, 22, 58])

In [39]:
x = x.reshape(5,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
y = y.reshape(5,10)
y

array([[53, 97, 41, 52, 46, 96, 97, 53, 79, 54],
       [12, 98, 82, 62, 88, 34, 74, 41, 14, 15],
       [25, 73, 28, 23, 57, 34, 95, 64, 33,  3],
       [16,  6, 14, 98, 20, 76, 47, 47, 39, 26],
       [45, 70, 42, 18, 25, 42,  7, 80, 22, 58]])

In [41]:
y.max()

98

In [42]:
y.min()

3

In [43]:
x.min()

0

In [44]:
y.argmax()

11

In [45]:
y.argmin()

29

In [47]:
x.shape

(5, 10)

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.shape

(3, 3)

In [50]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr = arr.reshape(1,9)

In [53]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
arr.shape

(1, 9)

In [55]:
arr.dtype

dtype('int32')