In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# broadcasting an array

In [6]:
arr[0:4] = 10

In [7]:
arr

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_of_array = arr[0:5]
slice_of_array

array([10, 10, 10, 10,  4])

Note: chnages made in slice of an array will also change the content of original array

In [9]:
slice_of_array[0:2] = 20
slice_of_array

array([20, 20, 10, 10,  4])

In [10]:
arr

array([20, 20, 10, 10,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_array[:] = 30
slice_of_array

array([30, 30, 30, 30, 30])

In [13]:
arr

array([30, 30, 30, 30, 30,  5,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy()
arr_copy

array([30, 30, 30, 30, 30,  5,  6,  7,  8,  9, 10])

In [15]:
arr_copy[0:3] = 10
arr_copy

array([10, 10, 10, 30, 30,  5,  6,  7,  8,  9, 10])

In [16]:
arr

array([30, 30, 30, 30, 30,  5,  6,  7,  8,  9, 10])

Note: changes made in a copy of array does not effect the original array

Copy array is only a view of the original array

# 2D Array

In [22]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr[2]

array([7, 8, 9])

In [24]:
arr[2][2]

9

In [25]:
#2d slicing of array

arr[:2,1:2]

array([[2],
       [5]])

In [27]:
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Fancy Indexing

In [28]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr = arr.reshape(5,5)

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr_length = arr.shape[1]
arr_length

5

In [43]:
for i in range(0,arr_length):
    arr[i] = i + 1
arr

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [37]:
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [39]:
arr[[1,2,3,4]]

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [40]:
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [44]:
arr[[0,1,2]]

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [45]:
arr[[4,2,1]]

array([[5, 5, 5, 5, 5],
       [3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2]])

# Selection

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [49]:
bool_arr = arr>2

In [50]:
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
another_array = arr[bool_arr]
another_array

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr3 = arr[arr>5]
arr3

array([ 6,  7,  8,  9, 10])